### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by kjirou** [kjirou/rails-vue-mpa#3]
## やる

- [ ] 送信するデータの型定義
- [ ] frontend_supperter 程の責務はいらなくて、webpack bridge とかそう言う程度でたりそう。
- [ ] articles をお題にサンプルアプリを作る。
- [ ] Vue の emits の型をちゃんと入れられるかの検証。
- [ ] サンプル程度に eslint の設定をする。
- [ ] welcome 用のページ数枚は erb で書く経路を作る。
- [ ] Rails のリンクをフロントで生成するロジック？

## やらない
